export const quotes = [
    // Život
{ text: "Život je ako bicykel. Aby si udržal rovnováhu, musíš sa hýbať.", author: "Albert Einstein", category: "Život" },
{ text: "Život je 10% to, čo sa ti stane, a 90% to, ako na to reaguješ.", author: "Charles R. Swindoll", category: "Život" },
{ text: "Život je krátky na to, aby sme ho trávili robením vecí, ktoré nemáme radi.", author: "Paulo Coelho", category: "Život" },
{ text: "Život je umenie bez návodu.", author: "Neznámy", category: "Život" },
{ text: "Život je cesta, nie cieľ.", author: "Ralph Waldo Emerson", category: "Život" },

// Motivácia
{ text: "Ak to dokážeš snívať, dokážeš to aj dosiahnuť.", author: "Walt Disney", category: "Motivácia" },
{ text: "Úspech je súčet malých snáh, ktoré sa opakujú každý deň.", author: "Robert Collier", category: "Motivácia" },
{ text: "Nikdy neprestávaj snívať, pretože sny sú začiatkom úspechu.", author: "Neznámy", category: "Motivácia" },
{ text: "Ak chceš niečo, čo si nikdy nemal, musíš urobiť niečo, čo si nikdy nerobil.", author: "Neznámy", category: "Motivácia" },
{ text: "Jediné obmedzenie, ktoré máme, je naša vlastná myseľ.", author: "Neznámy", category: "Motivácia" },

// Šťastie
{ text: "Šťastie je, keď to, čo myslíš, hovoríš a robíš, je v harmónii.", author: "Mahatma Gandhi", category: "Šťastie" },
{ text: "Šťastie nie je cieľ, je to spôsob života.", author: "Neznámy", category: "Šťastie" },
{ text: "Šťastie je vo vnútri, nie vo vonkajších veciach.", author: "Neznámy", category: "Šťastie" },
{ text: "Šťastie je, keď si uvedomíš, že máš všetko, čo potrebuješ.", author: "Neznámy", category: "Šťastie" },
{ text: "Šťastie je ako motýľ. Keď ho naháňaš, uniká ti. Keď si sadneš, pristane na tebe.", author: "Neznámy", category: "Šťastie" },

// Múdrosť
{ text: "Múdrosť prichádza s vekom, ale niekedy vek príde sám.", author: "Neznámy", category: "Múdrosť" },
{ text: "Múdrosť je pochopenie, že vždy existuje viac, ako vieme.", author: "Neznámy", category: "Múdrosť" },
{ text: "Múdrosť je schopnosť vidieť veci z viacerých uhlov pohľadu.", author: "Neznámy", category: "Múdrosť" },
{ text: "Múdrosť je pochopenie, že nič nie je čiernobiele.", author: "Neznámy", category: "Múdrosť" },
{ text: "Múdrosť je vedieť, čo robiť, keď nevieš, čo robiť.", author: "Neznámy", category: "Múdrosť" },


// SMRŤ
{ text: "Smrť nie je koniec. Je to len začiatok niečoho nového.", author: "Seneca", category: "Smrť" },
{ text: "Človek dvakrát neumiera – raz pri poslednom výdychu a druhýkrát, keď ho ľudia zabudnú.", author: "Ernest Hemingway", category: "Smrť" },
{ text: "Nič nie je určitejšie ako smrť a nič neistejšie ako jej hodina.", author: "Anselm z Canterbury", category: "Smrť" },
{ text: "Smrť nie je tragédiou. Tragédiou je život bez lásky.", author: "Leonardo da Vinci", category: "Smrť" },
{ text: "Keď sa bojíš smrti, bojíš sa života.", author: "Bertrand Russell", category: "Smrť" },
{ text: "Žijeme tak, akoby sme nikdy nemali zomrieť, a zomierame tak, akoby sme nikdy nežili.", author: "Dalajláma", category: "Smrť" },
{ text: "Dobrý človek sa smrti nebojí, lebo vie, že len mení svetlo.", author: "William Penn", category: "Smrť" },
{ text: "Smrť nie je najväčšia strata v živote. Najväčšia strata je to, čo v nás zomiera, kým ešte žijeme.", author: "Norman Cousins", category: "Smrť" },
{ text: "Život a smrť sú jedno, tak ako rieka a more.", author: "Kahlil Gibran", category: "Smrť" },
{ text: "Kým sa bojíš smrti, nikdy nebudeš skutočne žiť.", author: "Mark Twain", category: "Smrť" },

// LÁSKA
{ text: "Milovať a byť milovaný znamená cítiť slnko z oboch strán.", author: "David Viscott", category: "Láska" },
{ text: "Láska je jediná sila, ktorá dokáže premeniť nepriateľa na priateľa.", author: "Martin Luther King Jr.", category: "Láska" },
{ text: "Pravá láska nikdy neumiera.", author: "William Shakespeare", category: "Láska" },
{ text: "Milovať niekoho znamená vidieť zázrak, ktorý pre ostatných zostáva neviditeľný.", author: "Francois Mauriac", category: "Láska" },
{ text: "Láska nie je len cit. Je to rozhodnutie.", author: "Gary Chapman", category: "Láska" },
{ text: "Srdce má svoje dôvody, ktoré rozum nepozná.", author: "Blaise Pascal", category: "Láska" },
{ text: "Láska je kľúč, ktorý otvára bránu šťastia.", author: "Oliver Wendell Holmes", category: "Láska" },
{ text: "Keď milujeme, vždy sa snažíme byť lepšími, než sme.", author: "Paulo Coelho", category: "Láska" },
{ text: "Láska je ako vietor, nemôžeš ju vidieť, ale môžeš ju cítiť.", author: "Nicholas Sparks", category: "Láska" },
{ text: "Bez lásky je človek len tieňom samého seba.", author: "Johann Wolfgang von Goethe", category: "Láska" },
{ text: "Milovať niekoho znamená byť jediný, čo vidí zázrak, ktorý ostatní nevidia.", author: "Francois Mauriac", category: "Láska" },
{ text: "Láska rodí vždy len lásku.", author: "Sofoklés", category: "Láska" },
{ text: "Láska je závažie, ktoré ma ťahá nahor.", author: "Aurelius Augustinus", category: "Láska" },
{ text: "Keby na zemi vládla láska, nepotrebovali by sme zákony.", author: "Aristoteles", category: "Láska" },
{ text: "Zakaždým, keď ťa vidím, zamilujem sa znova.", author: "Alfred Tennyson", category: "Láska" },
{ text: "Väčšina ľudí sa domnieva, že láska znamená byť milovaný. Avšak pravda je opakom: láska znamená milovať.", author: "Erich Fromm", category: "Láska" },
{ text: "Láska je zo všetkých vášní najsilnejšia, lebo útočí zároveň na hlavu, srdce i telo.", author: "Voltaire", category: "Láska" },
{ text: "Nemilujem ťa preto, kto si, ale preto, kto som, keď som s tebou.", author: "Roy Croft", category: "Láska" },
{ text: "Najdôležitejšou vecou v živote je naučiť sa rozdávať lásku a nechať ju vstúpiť.", author: "Morrie Schwartz", category: "Láska" },
{ text: "Ak viem, čo je to láska, tak je to vďaka tebe.", author: "Hermann Hesse", category: "Láska" },
{ text: "Láska je pre človeka zložitejšia ako matematika, často s neriešiteľnými príkladmi.", author: "Albert Einstein", category: "Láska" },
{ text: "Na láske je najkrajšie to, že ju nikto nedokáže vysvetliť, ale predsa ju každý tak nádherne chápe.", author: "Francis Bacon", category: "Láska" },
{ text: "Keď niekoho milujeme, stáva sa naša láska reálnou a zjavnou len vďaka vynaloženej námahe vďaka tomu, že pre niekoho urobíme krok naviac alebo prejdeme celý kilometer. Láska vždy stojí úsilie; bez námahy sa k nej prísť nedá.", author: "Morgan Scott", category: "Láska" },
{ text: "Zamilovaní zatvárajú pri bozkávaní oči, pretože chcú vidieť srdcom.", author: "Daphne Du Maurier", category: "Láska" },
{ text: "Milujem život, pretože mi dal teba. Milujem teba, pretože ty si môj život.", author: "John Lennon", category: "Láska" },
{ text: "Je potrebné trochu sa podobať, aby sme si rozumeli, ale trochu sa líšiť, aby sme sa milovali.", author: "Jean Jacques Rousseau", category: "Láska" },


// KRESŤANSTVO
{ text: "Boh nepozerá na to, aké veľké veci robíme, ale koľko lásky do nich dávame.", author: "Matka Tereza", category: "Kresťanstvo" },
{ text: "Modlitba nie je nástroj na získanie vecí od Boha, ale spôsob, ako sa s ním spojiť.", author: "C.S. Lewis", category: "Kresťanstvo" },
{ text: "Lebo Boh tak miloval svet, že dal svojho jednorodeného Syna.", author: "Ján 3:16", category: "Kresťanstvo" },
{ text: "Nech je vaša viera väčšia ako váš strach.", author: "Neznámy", category: "Kresťanstvo" },
{ text: "Dôveruj Bohu celým srdcom a nespoliehaj sa na vlastný rozum.", author: "Príslovia 3:5", category: "Kresťanstvo" },
{ text: "Lebo s Bohom nič nie je nemožné.", author: "Lukáš 1:37", category: "Kresťanstvo" },
{ text: "Skutočná veľkosť človeka sa meria jeho vierou.", author: "Billy Graham", category: "Kresťanstvo" },
{ text: "Nikdy nepochybuj o Božej láske, aj keď nerozumieš Jeho ceste.", author: "Neznámy", category: "Kresťanstvo" },
{ text: "Všetko môžem v Kristovi, ktorý ma posilňuje.", author: "Filipanom 4:13", category: "Kresťanstvo" },
{ text: "Kto žije v láske, žije v Bohu a Boh v ňom.", author: "1. Ján 4:16", category: "Kresťanstvo" },

// PRIATEĽSTVO
{ text: "Skutočný priateľ je ten, kto prichádza, keď celý svet odchádza.", author: "Walter Winchell", category: "Priateľstvo" },
{ text: "Priateľstvo je ako kniha. Trvá chvíľu, kým ju spáliš, ale roky, kým ju napíšeš.", author: "Richard de Bury", category: "Priateľstvo" },
{ text: "Priateľ je dar, ktorý si dávaš sám.", author: "Robert Louis Stevenson", category: "Priateľstvo" },
{ text: "Pravý priateľ ťa nikdy nenechá ísť zlou cestou.", author: "Aristoteles", category: "Priateľstvo" },
{ text: "Nie je nič lepšieho na svete ako dobrý priateľ.", author: "Sokrates", category: "Priateľstvo" },

// STRACH
{ text: "Strach klepe na dvere. Keď otvorí viera, nikto tam nie je.", author: "Napoleon Bonaparte", category: "Strach" },
{ text: "Nebojme sa zajtrajška, lebo Boh je už tam.", author: "Charles Spurgeon", category: "Strach" },
{ text: "Najväčšia chyba, ktorú môžete urobiť, je báť sa, že nejakú urobíte.", author: "Elbert Hubbard", category: "Strach" },
{ text: "Strach je lož, ktorá sa tvári ako pravda.", author: "Robin Sharma", category: "Strach" },
{ text: "Nič v živote nie je treba sa báť, len pochopiť.", author: "Marie Curie", category: "Strach" },

// RODINA
{ text: "Rodina nie je len dôležitá vec, je to všetko.", author: "Michael J. Fox", category: "Rodina" },
{ text: "Šťastná rodina nie je nič iné ako skorší raj.", author: "George Bernard Shaw", category: "Rodina" },
{ text: "Rodina je tam, kde sa začína život a láska nikdy nekončí.", author: "Neznámy", category: "Rodina" },
{ text: "Môžete si vybrať priateľov, ale nie rodinu.", author: "Harper Lee", category: "Rodina" },
{ text: "Rodina je kompas, ktorý nás vedie. Je to inšpirácia k dosiahnutiu veľkých výšok a útočisko, keď sa potácame.", author: "Brad Henry", category: "Rodina" },
{ text: "Domov nie je miesto, ale pocit.", author: "Cecelia Ahern", category: "Rodina" },
{ text: "Rodina je jednou z prírodných majstrovských diel.", author: "George Santayana", category: "Rodina" },
{ text: "Rodina znamená, že nikto nezostane sám.", author: "Lilo & Stitch", category: "Rodina" },
{ text: "Najväčší dar, ktorý môžeš dať svojim deťom, je šťastná rodina.", author: "Neznámy", category: "Rodina" },
{ text: "Rodina je kotva v búrke života.", author: "Neznámy", category: "Rodina" },
{ text: "Rodina je miestom lásky a života. Miestom, kde láska rodí život.", author: "Ján Pavol II.", category: "Rodina" },
{ text: "Šťastný je ten, kto našiel šťastie v rodine.", author: "Lev Nikolajevič Tolstoj", category: "Rodina" },
{ text: "Svoju rodinu si nevyberáte. Tá je Božím darom pre vás, rovnako tak ako ste vy pre ňu.", author: "Desmond Tutu", category: "Rodina" },
{ text: "Šťastná rodina, nie je ničím iným, než predčasným nebom.", author: "George Bernard Shaw", category: "Rodina" },
{ text: "Rodina je prvou nevyhnutnou bunkou ľudskej spoločnosti.", author: "pápež Ján XXIII", category: "Rodina" },
{ text: "Nie je lepšieho daru, keď žije muž a žena ako jedno telo a duša v rodinnom kruhu.", author: "Homér", category: "Rodina" },
{ text: "Jediná skala, ktorá zostáva pevná, jediná inštitúcia, o ktorej viem, že funguje, je rodina.", author: "Süleyman I.", category: "Rodina" },
{ text: "Nezáležalo na tom, aký veľký bol náš dom; dôležité bolo, že v ňom bola láska.", author: "Peter Buffett", category: "Rodina" },
{ text: "Rodina, ktorá sa spoločne modlí, stojí pri sebe.", author: "Matka Tereza", category: "Rodina" },
{ text: "Môžeme mať svoje rozdiely, ale nič nie je dôležitejšie ako rodina.", author: "Coco", category: "Rodina" },
{ text: "Keď som mal 5 rokov, mamička mi povedala, že kľúčom života je šťastie. Keď som prišiel do školy, učiteľka sa ma spýtala, čím chcem byť, keď vyrastiem. Povedal som „šťastný“. Povedala mi, že som nerozumel otázke. Ja som povedal, že ona nerozumie životu.", author: "John Lennon", category: "Rodina" },
{ text: "Byť rodinou znamená, že ste súčasťou niečoho veľmi úžasného. Znamená to, že budete milovať a budete milovaní do konca života.", author: "Lisa Weedová", category: "Rodina" },
{ text: "Rodina – tá milá chobotnica, z ktorej chápadiel nikdy celkom neunikneme, ani si to v hĺbke srdca nikdy celkom neželáme.", author: "Dodie Smithová", category: "Rodina" },
{ text: "Bez rodiny sa človek trasie od zimy v nekonečnom vesmíre.", author: "André Maurois", category: "Rodina" },
{ text: "Domov je miesto, kde sídli láska, tvoria sa spomienky, priatelia sú vždy vítaní a smiech nikdy nekončí.", author: "Neznámy", category: "Rodina" },
{ text: "Priateľ vás môže milovať pre vašu inteligenciu, milenka pre váš pôvab, no rodina vás miluje bez dôvodu, lebo ste sa v nej narodili a ste kus jej tela.", author: "André Maurois", category: "Rodina" },
{ text: "Láska začína doma.", author: "Neznámy", category: "Rodina" },
{ text: "Spoločnosť, v ktorej je zasiahnutá rodina, nemá budúcnosť.", author: "Ján Pavol II.", category: "Rodina" },
{ text: "V čase skúšky je najlepšia rodina.", author: "barmské príslovie", category: "Rodina" },
{ text: "Život je krásny. Je to o dávaní. Je to o rodine.", author: "Walt Disney", category: "Rodina" },


// ZVIERATÁ
{ text: "Zvieratá sú najlepším priateľom človeka.", author: "Neznámy", category: "Zvieratá" },
{ text: "Keď má rád niekto samotu, je to buď divé zviera, alebo boh.", author: "Aristoteles", category: "Zvieratá" },
{ text: "Človek je najkrutejšie zviera.", author: "Friedrich Nietzsche", category: "Zvieratá" },
{ text: "V bájkach sú zvieratá ľudia. V živote je to naopak.", author: "Milovan Vitezovič", category: "Zvieratá" },
{ text: "Bude potrebné veľa vekov lásky, aby sme splatili zvieratám ich služby.", author: "Christian Morgenstern", category: "Zvieratá" },

// ĽUDIA
{ text: "Najzábavnejší ľudia sú najsmutnejší", author: "Konfucius", category: "Ľudia" },
{ text: "Tichí ľudia majú najhlasnejšiu myseľ.", author: "Stephen Hawking", category: "Ľudia" },
{ text: "Niektorí ľudia cítia dážď. Iní len zmoknú.", author: "Bob Marley", category: "Ľudia" },
{ text: "Je smutné, keď sa z niekoho, koho poznáte, stane niekto, koho ste poznali.", author: "Henry Rollins", category: "Ľudia" },
{ text: "Aj nekonečné more má svoje brehy, bezbrehá je len ľudská hlúposť.", author: "Konfucius", category: "Ľudia" },
{ text: "Pravda je taká, že každý ti raz ublíži. Musíš proste nájsť ľudí, pre ktorých sa oplatí trpieť.", author: "Bob Marley", category: "Ľudia" },
{ text: "Len dve veci sú nekonečné. Vesmír a ľudská hlúposť. Pri tej prvej si však nie som taký istý.", author: "Albert Einstein", category: "Ľudia" },
{ text: "Zaujímajte sa viac o svoj charakter ako o svoju reputáciu, pretože váš charakter je taký, aký v skutočnosti ste, zatiaľ čo vaša reputácia je iba odrazom toho, čo si ostatní myslia o vás.", author: "John Wooden", category: "Ľudia" },
{ text: "Charakter človeka môžete ľahko posúdiť podľa toho, ako sa správa k tým, ktorí pre neho nemôžu nič urobiť.", author: "Johann Wolfgang von Goethe", category: "Ľudia" },
{ text: "Možno by sa história nemusela opakovať, keby sme raz za čas počúvali.", author: "Wynne McLaughlin", category: "Ľudia" },
{ text: "Ľuďom nechýba sila, ale vôľa.", author: "Victor Hugo", category: "Ľudia" },
{ text: "Veľkí ľudia diskutujú o ideách, priemerní o udalostiach, a malí o iných ľuďoch.", author: "Charles de Gaulle", category: "Ľudia" },
{ text: "Keď prestanete od ľudí očakávať, že budú dokonalí, môžete ich mať radi takých, akí sú.", author: "Donald Miller", category: "Ľudia" },
{ text: "Nestrácajte čas vysvetľovaním: ľudia počujú len to, čo chcú počuť.", author: "Paulo Coelho", category: "Ľudia" },
{ text: "Ľudia často tvrdia, že túžia po pravde, ale málokedy im chutí, keď im ju niekto naservíruje.", author: "George R. R. Martin", category: "Ľudia" },
{ text: "Počas celého života vás budú ľudia rozčuľovať, znevažovať a zle sa k vám správať. Nechajte Boha, nech sa vysporiada s tým, čo robia, lebo nenávisť vo vašom srdci pohltí aj vás.", author: "Will Smith", category: "Ľudia" },
{ text: "Pravý charakter človeka sa ukáže, keď je opitý.", author: "Charlie Chaplin", category: "Ľudia" },
{ text: "Mám len jednu ambíciu. Mám len jednu vec, ktorú naozaj chcem, aby sa stala. Chcel by som vidieť ľudí spoločne žiť: čiernych, bielych, Číňanov, každého, to je všetko.", author: "Bob Marley", category: "Ľudia" },
{ text: "Nebezpečenstvom pre tento svet nie sú len ľudia, ktorí páchajú zlo, ale aj tí, čo sedia doma a dovolia im toto zlo páchať.", author: "Albert Einstein", category: "Ľudia" },
{ text: "Žiť, to je najvzácnejší dar na svete, pretože väčšina ľudí iba existuje.", author: "Oscar Wilde", category: "Ľudia" }
];